language: cpp

compiler:
    - gcc
#    - clang

before_install:
    - sudo apt-get install gfortran 
    - sudo apt-get install libgsl0-dev libgsl0ldbl
    - sudo apt-get install libblas-dev 
    - sudo apt-get install libhdf5-serial-dev
    - sudo apt-get install libfftw3-dev

script:
    - ./configure && make
