language: cpp

compiler:
    - gcc
#    - clang

before_install:
    - sudo apt-get install gfortran 
    - sudo apt-get install libgsl0-dev libgsl0ldbl
    - sudo apt-get install liblapack-dev
    - sudo apt-get install libhdf5-serial-dev
    - sudo apt-get install libfftw3-dev

script:
    - ./configure && make
#    - ./configure && make && make test
