language: cpp

compiler:
    - gcc
#    - clang

before_install:
    - sudo apt-get install gfortran 
    - sudo apt-get install gsl-bin 
    - sudo apt-get install libblas-dev 
    - sudo apt-get install libhdf5-serial-dev

script:
    - ./configure && make
